### ISSUE TITLE
Best system in ranking task

### ISSUE THREAD

**Issue by thpun** [paracrawl/keops#2]
Is it correct to assign "1" to the best among the candidates in ranking task?
Doc [here](https://github.com/paracrawl/keops/blob/master/evaluators.md#ranking) said:
>  Always start with best position in the ranking (1).

**Comment by sjarmero** [comment]
In the ranking task, you must rank the candidates starting at 1, which represents the best candidate among the others. If two translations are identical, you can assign the same number to them.

**Comment by thpun** [comment]
I got this question because in ran.php, the best system is the one with the least '1' among all. (Is my understanding correct?)
Line 311 is sorting in ascending order.
https://github.com/paracrawl/keops/blob/ef34f9e99ce360ef14b3ea2c80193f148fd30ee6/tasks/recap/ran.php#L308-L315

**Comment by sjarmero** [comment]
Sorry for the delay @thpun 

You are right! By ordering in ascending order we are showing the worst systems as the best ones. This will be fixed shortly in `master`. However, I would like to point out that this only affects ordering when showing data, both evaluation and raw data are correctly stored. Thanks for your insight!
