### ISSUE TITLE
Summary of fluency task does not match with statistics in recap

### ISSUE THREAD

**Issue by thpun** [paracrawl/keops#3]
Statistics shown in recap is like this:
![image](https://user-images.githubusercontent.com/31913095/107482340-84246980-6bba-11eb-937d-9b5157b21d90.png)

But the downloaded summary is like this:
![image](https://user-images.githubusercontent.com/31913095/107482421-9acac080-6bba-11eb-8757-b4a50f0284ff.png)

**Comment by sjarmero** [comment]
Thanks for the heads-up @thpun! Fixed and uploaded to master
